query ($number: Int!) {
  repository(owner: "kthatoto", name: "hatotology") {
    issue(number: $number) {
      title
      body
      createdAt
      updatedAt
      labels(first: 10) {
        nodes {
          name
        }
      }
      comments(first: 10) {
        nodes {
          body
          author {
            avatarUrl
            login
          }
        }
      }
    }
  }
}
