query ($count: Int!) {
  repository(owner: "kthatoto", name: "hatotology") {
    issues(
      last: $count,
      orderBy: {field: CREATED_AT, direction: DESC},
      states: OPEN
    ) {
      nodes {
        title
        number
        createdAt
      }
    }
  }
}
